version: '3.5'
services:
 
  fe-bookwave:
    container_name: fe-bookwave
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '4200:4200'
